language: java
jdk:
- oraclejdk8
notifications:
  email:
  - sascha.feldmann@gmx.de
addons:
  apt:
    packages:
    - sshpass
after_success:
- bash <(curl -s https://codecov.io/bash)
- curl -T /home/travis/build/sasfeld-thesis/question-generator/qg-portlet/target/qg-portlet.war -u $TESTING_DEPLOYMENT_USER:$TESTING_DEPLOYMENT_PW $TESTING_DEPLOYMENT_PATH
